baseURL = 'https://Lofter1.github.io/UMT-VM-Gallery/'
languageCode = 'en-us'
title = 'UTM Gallary'
sectionPagesMenu = "main"

[params]
    github = 'https://github.com/Lofter1/UMT-VM-Gallery'
    github_issues = 'https://github.com/Lofter1/UMT-VM-Gallery'
